version: '3.1'
services:
  mysql-microservice:
    image: mysql:8.0
    container_name: container_mysql-microservice
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-microservice:
    container_name: container_phpmyadmin-microservice
    image: phpmyadmin/phpmyadmin
    ports:
      - '8085:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-microservice
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-microservice
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin
networks:
  zipkin:
    driver: bridge


volumes:
  mysql_data:
    driver: local

