eureka:
  client:
    register-with-eureka: false

spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id:  teachers
          uri: http://localhost:8090
          predicates:
            - Path= /api/v1/teachers/**

        - id: schools
          uri: http://localhost:9999
          predicates:
            - Path= /api/v1/schools/**
        - id: students
          uri: http://localhost:9090
          predicates:
            - Path = /graphiql



server:
  port: 8222

