eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9999
spring:
  application:
    name: ms2
  datasource:
    username: user
    password: user
    url: jdbc:mysql://localhost:3306/microservice_db
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

management:
  tracing:
    sampling:
      probability: 1.0